CREATE TABLE cn_stock_master (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    code VARCHAR(10) NOT NULL COMMENT '股票代码，如 600519',
    name VARCHAR(64) NOT NULL COMMENT '股票名称',
    exchange VARCHAR(8) NOT NULL COMMENT '交易所，SSE/SZSE/BSE',
    market VARCHAR(16) NOT NULL COMMENT '市场类型，main/gem/star/beijing',
    industry VARCHAR(128) NULL COMMENT '所属行业',
    area VARCHAR(64) NULL COMMENT '所属地域',
    list_status VARCHAR(16) NOT NULL COMMENT '上市状态，listed/delisted/suspended',
    is_risk_warning BOOL NOT NULL COMMENT '是否风险警示股，1是 0否',
    list_date DATE NULL COMMENT '上市日期',
    delist_date DATE NULL COMMENT '退市日期',
    is_active BOOL NOT NULL COMMENT '是否有效，1有效 0无效',
    source VARCHAR(32) NOT NULL COMMENT '数据来源，如 tushare/baostock/manual',
    source_updated_at DATETIME NULL COMMENT '源数据更新时间',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cn_stock_master_code (code),
    KEY idx_cn_stock_master_name (name),
    KEY idx_cn_stock_master_exchange_market (exchange, market),
    KEY idx_cn_stock_master_industry (industry),
    KEY idx_cn_stock_master_list_status (list_status),
    KEY idx_cn_stock_master_is_risk_warning (is_risk_warning),
    KEY idx_cn_stock_master_is_active (is_active)
) COMMENT='A股股票主数据表';
